name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main", "master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3  # Aggiungi questo step per ottenere il SHA
        
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: franky-04
          committer_token: ${{ secrets.GITHUB_TOKEN }}  # Aggiungi questo parametro
          output_action: commit
          
          # Configurazione base
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Rome
          
          # Modifica queste impostazioni per focalizzarti sui dati essenziali
          base_indepth: yes
          repositories_forks: no       # Evita di analizzare i fork per ridurre gli errori
          repositories_affiliations: owner, collaborator, organization_member
          
          # Riduzione del numero di plugin per evitare errori
          plugin_lines: yes
          plugin_languages: yes
          plugin_isocalendar: yes
